FROM python:3.13
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY ./sshrest.py /app/app.py

CMD ["fastapi", "run", "app.py", "--port", "80"]